# -*- coding: utf-8 -*-
"""Descriptive statistics.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HGZ0BJvMfyfmWavwipALdnDbAS4W7WVK
"""

import pandas as pd
import os
import glob

from google.colab import drive
drive.mount('/content/gdrive')
path = "/content/gdrive/MyDrive/Especialidad - IA/IA 2/Reto/Descriptive statistics/dummies_data"

complete_stats = pd.DataFrame()

selected_files = ['example0', 'example10', 'example20', 'example30', 'example40', 'example50', 'example60', 'example70', 'example80', 'example90']
stats_dic = {}

for file_name in selected_files:
  file = glob.glob(f'{path}/{file_name}.csv', recursive=False)
  df = pd.read_csv(file[0])
  stats = df.describe()
  stats = stats.transpose()
  stats_dic[file_name] = stats

complete_stats = pd.concat(stats_dic).reset_index()

complete_stats.rename(columns = {'level_0':'file', 'level_1':'variable'}, inplace = True)
complete_stats.set_index(['file', 'variable'], inplace=True)

complete_stats

